# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeaningPush' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PGFramework'
  pod 'Alamofire'
  # Pods for LeaningPush

end
